- name: "Visual Studio Code | パッケージを最新化する"
  become: yes
  apt:
    name: '*'
    state: latest

- name: "Visual Studio Code | Snapをインストールする"
  ignore_errors: "{{ ansible_check_mode }}"
  become: yes
  apt:
    name: snapd
    state: present

- name: "Visual Studio Code | インストールする"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  shell: snap install --classic code

